version: 2
jobs:
  master_build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build and upload sample debug to firebase
          command: ./gradlew assembleExternalRelease -PversionCode=$CIRCLE_BUILD_NUM appDistributionUploadExternalRelease
workflows:
  version: 2
  build_app:
    jobs:
      - master_build:
          filters:
            branches:
              only: master
